### ISSUE TITLE
Where to get .bin file to update firmware?

### ISSUE THREAD

**Issue by doctea** [nobomi/Arduino-ARMSID-configurator#3]
Hi, I have just built the programming shield, and can access the armsid tester software via puTTY, etc.  However I can't find the .bin file to update my ARMSID to the latest version?  (mine says FW VERSION:2.9)

I also do not see as many options as in the screenshots when using the armsid tester software -- I only see options for 6/7/8,P,E,R,Q.  It says version 3.13.  Is this normal?

Thanks,

**Comment by mlukasek** [comment]
The screenshots are from ARM**2**SID, not ARMSID, so there are more options there. ARMSID firmware version is 2.XX, while ARM2SID version numbers are 3.XX. We try to keep the feature set the same, so XX is real version number ;-)

I have sent you the binary updater firmware to your gmail. Just unzip it and use asid213.bin to update your ARMSID to fw2.13. It is encrypted, so you must use the updater and integrated bootloader. Do not try to flash the firmware with any ST tools, otherwise you will delete the ARMSID integrated bootloader and brick you ARMSID.

**Comment by doctea** [comment]
Thank you, all updated and running well!  Also, it seemed that I get more options in the tester (ie ADSR bug fix menu) after I updated the firmware :).
